### ISSUE TITLE
Curated Culture

### ISSUE THREAD

**Issue by Tochiisan** [wacko1805/google-pixel-wallpapers#2]
Disability Pride, Disability and Nature, Disability Diversity

**Comment by Tochiisan** [comment]
![IMG_20211207_010032](https://user-images.githubusercontent.com/92343311/144889765-4a24a5ea-7e79-4b8a-84c9-85cb8e65b8a6.jpg)
![IMG_20211207_010034](https://user-images.githubusercontent.com/92343311/144889779-bf685051-43f1-4a57-849e-8a02ece90e0e.jpg)
![IMG_20211207_010037](https://user-images.githubusercontent.com/92343311/144889786-adbbd082-8e57-47bd-a73e-ffd799315300.jpg)

**Comment by wacko1805** [comment]
Added, thank you!
